force-app/main/default/objects/EventQueue__c/EventQueue__c.object-meta.xml
<CustomObject>
    <description>Message Events</description>
    <label>EventQueue</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>EventQueue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EventQueues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EventQueue__c/fields/EventName__c.field-meta.xml
<CustomField>
    <fullName>EventName__c</fullName>
    <description>EventName</description>
    <label>EventName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of event</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>QUEUED</fullName>
                <default>true</default>
                <label>QUEUED</label>
            </value>
            <value>
                <fullName>DELIVERED</fullName>
            </value>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>INVALID</fullName>
            </value>
            <value>
                <fullName>SCHEDULED</fullName>
            </value>
            <value>
                <fullName>UNHANDLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/event/builder/EventQueueBuilderTest.cls
@isTest
public class EventQueueBuilderTest {

    @isTest
    static void shouldConvertEventQueueToQueueEvents() {
        // Given: Criar uma lista de EventQueue usando a FixtureFactory
        List<EventQueue> events = EventQueueFixtureFactory.newEvents(3);

        List<EventQueue__c> result =  new EventQueueBuilder().convertToQueueEvents(events);

        // Then: Verificar se os eventos foram convertidos corretamente
        System.assertEquals(3, result.size(), 'O número de eventos convertidos deve ser igual ao número de eventos fornecidos.');
        for (Integer i = 0; i < result.size(); i++) {
            System.assertEquals('Event ' + i, result[i].EventName__c, 'O nome do evento convertido deve corresponder ao evento original.');
            System.assertEquals('QUEUED' , result[i].Status__c, 'O tipo do evento convertido deve corresponder ao evento original.');
        }
    }

    @isTest
    static void shouldHandleEmptyEventQueueList() {
        // Given: Uma lista vazia de EventQueue
        List<EventQueue> eventQueues = new List<EventQueue>();

        // When: Invocar o método convertToQueueEvents
        EventQueueBuilder builder = new EventQueueBuilder();
        List<EventQueue__c> result = builder.convertToQueueEvents(eventQueues);

        // Then: Verificar se o resultado é uma lista vazia
        System.assertEquals(0, result.size(), 'O resultado deve ser uma lista vazia quando nenhuma entrada é fornecida.');
    }
}