force-app/main/default/objects/EventQueue__c/EventQueue__c.object-meta.xml
<CustomObject>
    <description>Message Events</description>
    <label>EventQueue</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>EventQueue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EventQueues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EventQueue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of event</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>QUEUED</fullName>
                <default>true</default>
                <label>QUEUED</label>
            </value>
            <value>
                <fullName>DELIVERED</fullName>
            </value>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>INVALID</fullName>
            </value>
            <value>
                <fullName>SCHEDULED</fullName>
            </value>
            <value>
                <fullName>UNHANDLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/event/consumer/test/EnqueueEventsInBatchTest.cls
@isTest
public class EnqueueEventsInBatchTest implements Database.Batchable<SObject> {

    public EnqueueEventsInBatchTest() {
    }

    public Database.QueryLocator start(Database.BatchableContext context) {
        // Retorna uma consulta fictícia apenas para simular o Batch
        return Database.getQueryLocator([SELECT Id FROM User]);
    }

    public void execute(Database.BatchableContext context, List<SObject> scope) {

        EventQueueFixtureFactory.createEventQueues(2);

    }

    public void finish(Database.BatchableContext context) {

    }


    @isTest
    static void shouldChangeStatusToScheduledInBatchContext() {

        // Simula o contexto de Batch
        Test.startTest();

        Database.executeBatch(new EnqueueEventsInBatchTest());
    
        Test.stopTest();

        List<EventQueue__c> events = [ SELECT Id, Status__c FROM EventQueue__c];

        Assert.areEqual( 2, events.size(), 'Expected two events');

        // Então (Then)
        for (EventQueue__c event : events) {
            System.assertEquals(
                EventQueueStatusType.SCHEDULED.name(),
                event.Status__c,
                'Status should be updated to Scheduled in Batch context'
            );
        }
    }


}