force-app/main/default/objects/EventQueue__c/EventQueue__c.object-meta.xml
<CustomObject>
    <description>Message Events</description>
    <label>EventQueue</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>EventQueue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EventQueues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EventQueue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of event</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>QUEUED</fullName>
                <default>true</default>
                <label>QUEUED</label>
            </value>
            <value>
                <fullName>DELIVERED</fullName>
            </value>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>INVALID</fullName>
            </value>
            <value>
                <fullName>SCHEDULED</fullName>
            </value>
            <value>
                <fullName>UNHANDLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/event/publisher/BaseEventPublisherTest.cls
@isTest
public class BaseEventPublisherTest {

    @isTest
    static void shouldMockPublishEventsSuccessfully() {
        
        List<Account> accounts = new List<Account> {
            AccountFixtureFactory.newWithFakeId(StringGenerator.text(10))
        };

        String eventName = 'SyncAccountOutbound';

        
        EventQueueRepository repositoryMock = new EventQueueRepositoryTest.EventQueueRepositoryMock();

        BaseEventPublisher publisher = new BaseEventPublisher(repositoryMock);
        
        List<EventQueue__c> events = publisher.publish(eventName,accounts);

        Assert.areEqual('QUEUED', events.get(0).Status__c);
        Assert.isNotNull( events.get(0).Id );

    }

    @isTest
    static void shouldPublishEventsSuccessfully() {
        
        List<Account> accounts = new List<Account> {
            AccountFixtureFactory.newWithFakeId(StringGenerator.text(10))
        };

        String eventName = 'SyncAccountOutbound';

        BaseEventPublisher publisher = new BaseEventPublisher();
        
        List<EventQueue__c> events = publisher.publish(eventName,accounts);
        
        Assert.areEqual('QUEUED', events.get(0).Status__c);
        Assert.isNotNull( events.get(0).Id );

    }

}