force-app/main/default/objects/EventQueue__c/EventQueue__c.object-meta.xml
<CustomObject>
    <description>Message Events</description>
    <label>EventQueue</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>EventQueue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EventQueues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EventQueue__c/fields/CorrelatedNumber__c.field-meta.xml
<CustomField>
    <fullName>CorrelatedNumber__c</fullName>
    <description>Business Document Correlated Number</description>
    <label>CorrelatedNumber</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/fields/DetailedStatus__c.field-meta.xml
<CustomField>
    <fullName>DetailedStatus__c</fullName>
    <description>Error Message from internal or external System</description>
    <label>DetailedStatus</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <description>DocumentNumber</description>
    <label>DocumentNumber</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/fields/EventName__c.field-meta.xml
<CustomField>
    <fullName>EventName__c</fullName>
    <description>EventName</description>
    <label>EventName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/fields/IsRetryDisabled__c.field-meta.xml
<CustomField>
    <fullName>IsRetryDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identify if the retries should be executed for this event. If equal TRUE disable retries even if retry count is bigger than zero (can be used for errors as errors does not require retries)</description>
    <label>IsRetryDisabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/fields/RetryCount__c.field-meta.xml
<CustomField>
    <fullName>RetryCount__c</fullName>
    <defaultValue>10</defaultValue>
    <description>Identify the number of retries for this event</description>
    <label>RetryCount</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/fields/SalesforceObjectId__c.field-meta.xml
<CustomField>
    <fullName>SalesforceObjectId__c</fullName>
    <description>Salesforce Object Id</description>
    <label>SalesforceObjectId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of event</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>QUEUED</fullName>
                <default>true</default>
                <label>QUEUED</label>
            </value>
            <value>
                <fullName>DELIVERED</fullName>
            </value>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>INVALID</fullName>
            </value>
            <value>
                <fullName>SCHEDULED</fullName>
            </value>
            <value>
                <fullName>UNHANDLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/event/test/EventQueueFixtureFactory.cls
@isTest
public class EventQueueFixtureFactory {

    public static EventConfiguration newBaseConfig (String eventName) {
        return EventConfigurationFixtureFactory.newEventConfiguration(eventName);
    }

    public static EventQueue__c newEventQueue (String name) {
        return newEventQueue(name, EventQueueStatusType.QUEUED.name() );
    }

    public static EventQueue__c newEventQueue (String name, String status) {
        
        return new EventQueue__c(
            EventName__c = name,
            Status__c = status,
            RetryCount__c = 10,
            ExternalId__c = StringGenerator.text(10),
            SalesforceObjectId__c = IdGenerator.generate ( new Order() ).Id            
        );

    }
    
    public static List<EventQueue__c> newEventQueues(Integer count) {

        List<EventQueue__c> events = new List<EventQueue__c>();
        for (Integer i = 0; i < count; i++) {
            events.add(newEventQueue('Event ' + i));
        }
        return events;
    }

    public static List<EventQueue__c> newEventQueues(List<String> statuses) {

        List<EventQueue__c> eventQueues = new List<EventQueue__c>();

        Integer i = 0;

        for (String status : statuses) {
            eventQueues.add(newEventQueue( 'Event ' + i, status));
            i++;
        }

        return eventQueues;
    }

    public static List<EventQueue__c> createEventQueues(Integer count) {
        return save ( newEventQueues(count) );
    }
    
    public static EventQueue__c createEventQueue (String eventName) {
        return save ( newEventQueue(eventName) );
    }

    public static EventQueue__c createEventQueue (String eventName, String status) {
        return save ( newEventQueue(eventName, status) );
    }

    public static EventQueue newEvent (String name, String commandClassName) {   

        EventConfiguration config = newBaseConfig(name)
                                        .commandClassName (commandClassName);

        return new EventQueue( newEventQueue(name) )
                    .withConfiguration( config );
    }

    public static EventQueue newEvent (String name, Command command) {   
        return new EventQueue( newEventQueue(name) )
                    .withConfiguration(newBaseConfig(name))
                    .withCommand(command);
    }

    public static EventQueue newEvent (String name) {   
        return new EventQueue( newEventQueue(name) )
                    .withConfiguration(newBaseConfig(name));
    }

    public static EventQueue newEventWithOutboundConfig (String name, String responseClasseName) {   
        return new EventQueue( newEventQueue(name) )
                    .withConfiguration( 
                        EventConfigurationFixtureFactory.newEventConfigurationForOutbound(name, responseClasseName));
    }

    public static EventQueue newOAuthEventWithOutboundConfig (String name, String responseClasseName) {   
        return new EventQueue( newEventQueue(name) )
                    .withConfiguration( 
                        EventConfigurationFixtureFactory.newOAuthEventConfigurationForOutbound(name, responseClasseName));
    }
    

    public static List<EventQueue> newEvents(Integer size) {
        
        List<EventQueue> eventQueues = new List<EventQueue>();
        
        for (Integer i = 0; i < size; i++) {
            eventQueues.add( newEvent ('Event ' + i));
        }

        return eventQueues;
    }

    public static List<EventQueue__c> save (List<EventQueue__c> events) {
        upsert events;
        return events;
    }

    public static EventQueue__c save (EventQueue__c event) {
        save(new List<EventQueue__c> {event});
        return event;
    }

    public static EventQueue__c findByEventName (String eventName) {

        return [SELECT Id, EventName__c, ExternalId__c
                    , DocumentNumber__c, CorrelatedNumber__c, SalesforceObjectId__c
                    , RetryCount__c , IsRetryDisabled__c
                    , Status__c , DetailedStatus__c        
                FROM EventQueue__c
                WHERE EventName__c = :eventName];

    }

}