force-app/main/default/objects/EventQueue__c/EventQueue__c.object-meta.xml
<CustomObject>
    <description>Message Events</description>
    <label>EventQueue</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>EventQueue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EventQueues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EventQueue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of event</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>QUEUED</fullName>
                <default>true</default>
                <label>QUEUED</label>
            </value>
            <value>
                <fullName>DELIVERED</fullName>
            </value>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>INVALID</fullName>
            </value>
            <value>
                <fullName>SCHEDULED</fullName>
            </value>
            <value>
                <fullName>UNHANDLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/event/consumer/EventQueueInterceptorTest.cls
@isTest
public class EventQueueInterceptorTest {

    @isTest
    static void shouldNotChangeStatusWhenNotInBatchOrFutureContext() {
                
        List<EventQueue__c> events = EventQueueFixtureFactory.newEventQueues(3);

        new EventQueueInterceptor().onBatchOrFutureAutoScheduleEvents(events);

        for (EventQueue__c event : events) {
            Assert.areEqual( EventQueueStatusType.QUEUED.name()
                            , event.Status__c
                            , 'Status should remain unchanged when not in Batch or Future context');
        }

    }

    @isTest
    static void shouldChangeToScheduleEnqueuedEventsCloseLimits () {
        
        EventDequeuer.executedFutureCalls = 40;

        List<EventQueue__c> events = EventQueueFixtureFactory.newEventQueues(300);

        new EventQueueInterceptor().onFutureLimitClosedAutoScheduleEvents(events);

        Filter filter = new Filter();
        
        List<EventQueue__c> queuedEvents = filter.byValue(events, 'Status__c', EventQueueStatusType.QUEUED.name());

        List<EventQueue__c> scheduledEvents = filter.byValue(events, 'Status__c', EventQueueStatusType.SCHEDULED.name());
        
        Assert.areEqual(75, scheduledEvents.size());

        Assert.areEqual(225, queuedEvents.size());

    }

}