force-app/main/default/objects/EventQueue__c/EventQueue__c.object-meta.xml
<CustomObject>
    <description>Message Events</description>
    <label>EventQueue</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>EventQueue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EventQueues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EventQueue__c/fields/EventName__c.field-meta.xml
<CustomField>
    <fullName>EventName__c</fullName>
    <description>EventName</description>
    <label>EventName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/event/executor/EventExecutor.cls
public virtual class EventExecutor extends AbstractEventExecutor {

    //4 Inject Mock
    @TestVisible
    static EventExecutor executor;

    static {
        executor = new EventExecutor();
    }

    @future(callout=true)
    public static void execute (List<String> eventIds) {
        executor.initializeEvents(eventIds).execute();
    }

    EventConfigurationFilter configFilter;
    
    public EventExecutor() {

        super ( new List<AbstractEventExecutor> {
                            new EventCalloutExecutor()
                            , new EventUpdateExecutor() }
        );
        
        this.configFilter = new EventConfigurationFilter();

    }

    public EventExecutor(List<String> eventIds) {
        this();
        this.events = findEvents(eventIds);
    }

    public EventExecutor(List<EventQueue> events) {
        this();
        this.events = events;
    }

    public EventExecutor initializeEvents(List<String> eventIds) {
        this.events = findEvents(eventIds);
        return this;
    }

    protected List<EventQueue> findEvents (List<String> eventIds) {

        List<EventQueue__c> queues = repository.findByIds(eventIds);

        Map<String, EventConfiguration> configs = configFilter.indexByName ( repository.findConfigByNames ( 
                                                                                    Lists.pullField ( queues, 'EventName__c' )
                                                                            ));
        List<EventQueue> events = new List<EventQueue>();

        for (EventQueue__c queue : queues ) {

            events.add ( new EventQueue ( queue
                                        , configs.get(queue.EventName__c)
                                        , this.repository ) );
        }

        return events;

    }    

}