force-app/main/default/objects/EventQueue__c/EventQueue__c.object-meta.xml
<CustomObject>
    <description>Message Events</description>
    <label>EventQueue</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>EventQueue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EventQueues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EventQueue__c/fields/EventName__c.field-meta.xml
<CustomField>
    <fullName>EventName__c</fullName>
    <description>EventName</description>
    <label>EventName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/fields/SalesforceObjectId__c.field-meta.xml
<CustomField>
    <fullName>SalesforceObjectId__c</fullName>
    <description>Salesforce Object Id</description>
    <label>SalesforceObjectId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of event</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>QUEUED</fullName>
                <default>true</default>
                <label>QUEUED</label>
            </value>
            <value>
                <fullName>DELIVERED</fullName>
            </value>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>INVALID</fullName>
            </value>
            <value>
                <fullName>SCHEDULED</fullName>
            </value>
            <value>
                <fullName>UNHANDLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/event/publisher/BaseEventPublisher.cls
public virtual class BaseEventPublisher {

    EventQueueRepository repository;

    public BaseEventPublisher() {
        repository = new EventQueueRepository();
    }

    //4 test injection
    public BaseEventPublisher(EventQueueRepository repository) {
        this.repository = repository;
    }    

    public List<EventQueue__c> publish ( String eventName, List<SObject> records ) {
        List<EventQueue__c> events = new List<EventQueue__c>();

        for (SObject record : records ) {
            events.add( buildEvent( eventName, record));
        }

        return repository.save(events);

    }

    virtual
    public EventQueue__c buildEvent (String eventName, SObject record) {        

        return new EventQueue__c ( EventName__c = eventName
            , Status__c = EventQueueStatusType.QUEUED.name() 
            , SalesforceObjectId__c = record.Id
        );

    }

}