force-app/main/default/objects/EventQueue__c/EventQueue__c.object-meta.xml
<CustomObject>
    <description>Message Events</description>
    <label>EventQueue</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>EventQueue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EventQueues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EventQueue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of event</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>QUEUED</fullName>
                <default>true</default>
                <label>QUEUED</label>
            </value>
            <value>
                <fullName>DELIVERED</fullName>
            </value>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>INVALID</fullName>
            </value>
            <value>
                <fullName>SCHEDULED</fullName>
            </value>
            <value>
                <fullName>UNHANDLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/event/job/AbstractEnqueueEventsStrategy.cls
public inherited sharing abstract class AbstractEnqueueEventsStrategy {

    private EventQueueRepository repository;

    public AbstractEnqueueEventsStrategy() {
        repository = new EventQueueRepository();
    }

    public void enqueue () {

        List<EventQueue__c> events = findEvents();

        for (EventQueue__c event : events) {
            event.Status__c = EventQueueStatusType.QUEUED.name();
        }

        repository.save(events);

    }

    public abstract List<EventQueue__c> findEvents ();

    public abstract Integer getJobInterval ();

    public EventQueueRepository getRepository () {
        return repository;
    }

}