force-app/main/default/objects/EventQueue__c/EventQueue__c.object-meta.xml
<CustomObject>
    <description>Message Events</description>
    <label>EventQueue</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>EventQueue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EventQueues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EventQueue__c/fields/DetailedStatus__c.field-meta.xml
<CustomField>
    <fullName>DetailedStatus__c</fullName>
    <description>Error Message from internal or external System</description>
    <label>DetailedStatus</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/fields/EventName__c.field-meta.xml
<CustomField>
    <fullName>EventName__c</fullName>
    <description>EventName</description>
    <label>EventName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/fields/IsRetryDisabled__c.field-meta.xml
<CustomField>
    <fullName>IsRetryDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identify if the retries should be executed for this event. If equal TRUE disable retries even if retry count is bigger than zero (can be used for errors as errors does not require retries)</description>
    <label>IsRetryDisabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/fields/RetryCount__c.field-meta.xml
<CustomField>
    <fullName>RetryCount__c</fullName>
    <defaultValue>10</defaultValue>
    <description>Identify the number of retries for this event</description>
    <label>RetryCount</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/fields/SalesforceObjectId__c.field-meta.xml
<CustomField>
    <fullName>SalesforceObjectId__c</fullName>
    <description>Salesforce Object Id</description>
    <label>SalesforceObjectId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of event</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>QUEUED</fullName>
                <default>true</default>
                <label>QUEUED</label>
            </value>
            <value>
                <fullName>DELIVERED</fullName>
            </value>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>INVALID</fullName>
            </value>
            <value>
                <fullName>SCHEDULED</fullName>
            </value>
            <value>
                <fullName>UNHANDLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/event/test/EventQueueTest.cls
@isTest
public class EventQueueTest {

    @isTest
    static void shouldInitializeEventQueueWithConfig() {
        // Given
        EventQueue__c eventQueueRecord = EventQueueFixtureFactory.createEventQueue ('TestEvent', 'UNHANDLED');
        EventQueueRepository mockRepository = new EventQueueRepository();
        EventConfiguration mockConfig = new EventConfiguration();

        // When
        EventQueue eventQueue = new EventQueue(eventQueueRecord, mockConfig, mockRepository);

        // Then
        System.assertEquals('TestEvent', eventQueue.getSObject().EventName__c);
        System.assertEquals('UNHANDLED', eventQueue.getStatus());
        System.assertEquals(eventQueueRecord.ExternalId__c, eventQueue.getExternalId());
        System.assertEquals(eventQueueRecord.SalesforceObjectId__c, eventQueue.getObjectId());

        Assert.isFalse( eventQueue.useCustomOAuthFlow() );
        
        Assert.isFalse( eventQueue.hasError() );

        Assert.isTrue( eventQueue.isUnhandled() );

        Assert.isFalse( eventQueue.hasHandler() );

        Assert.isNull( eventQueue.getOutboundConfig() );
       
        Assert.isNull( eventQueue.getCommand() , 'Não há handler configurado para esse evento');
                

    }

    @isTest
    public static void shouldInitializeEventByNameWithEmptyConfig () {
        
        EventQueue event = new EventQueue('TestEvent');

        Assert.isNull(event.getConfig());
        
    }

    @isTest
    static void shouldReturnOAuthEvent() {

        EventQueue__c eventQueueRecord = EventQueueFixtureFactory.newEventQueue ('TestEvent', 'UNHANDLED');
                
        EventQueue eventQueue = new EventQueue(eventQueueRecord, 
             EventConfigurationFixtureFactory.newEventConfiguration('TestEvent')
            , new EventQueueRepositoryTest.EventQueueRepositoryConfigMock() );

        EventQueue oauthEvent = eventQueue.getOAuthEvent();

        Assert.isNotNull( oauthEvent , 'É esperado um evento de autenticação' );

    }

     
    @isTest
    static void shouldMarkEventQueueAsDelivered() {
        // Given
        EventQueue__c eventQueueRecord = EventQueueFixtureFactory.newEventQueue('TestEvent', 'UNHANDLED');
        EventQueue eventQueue = new EventQueue(eventQueueRecord);

        // When
        eventQueue.delivered();

        // Then
        System.assertEquals('DELIVERED', eventQueue.getStatus());
        System.assertEquals('', eventQueue.getSObject().DetailedStatus__c);
    }

    @isTest
    static void shouldHandleErrorCorrectly() {
        // Given
        EventQueue__c eventQueueRecord = EventQueueFixtureFactory.newEventQueue('TestEvent', 'UNHANDLED');
        EventQueue eventQueue = new EventQueue(eventQueueRecord);
        IntegrationBusinessException testException = new IntegrationBusinessException('Code','Test Exception');

        // When
        eventQueue.withError(testException);

        // Then
        System.assertEquals('ERROR', eventQueue.getStatus());
        System.assert(eventQueue.getSObject().DetailedStatus__c.contains('Test Exception'));
    }

    @isTest
    static void shouldDecreaseRetryCount() {
        // Given
        EventQueue__c eventQueueRecord = EventQueueFixtureFactory.newEventQueue('TestEvent');
        EventQueue eventQueue = new EventQueue(eventQueueRecord);

        // When
        eventQueue.decreaseRetry();

        // Then
        System.assertEquals(9, eventQueue.getSObject().RetryCount__c);
    }

    @isTest
    static void shouldDisableRetry() {
        // Given
        EventQueue__c eventQueueRecord = EventQueueFixtureFactory.newEventQueue('TestEvent');
        EventQueue eventQueue = new EventQueue(eventQueueRecord);

        // When
        eventQueue.disableRetry();

        // Then
        System.assertEquals(0, eventQueue.getSObject().RetryCount__c);
        System.assertEquals(true, eventQueue.getSObject().IsRetryDisabled__c);
    }

    @isTest
    static void shouldSaveEventQueue() {
        // Given
        EventQueue__c eventQueueRecord = EventQueueFixtureFactory.newEventQueue('TestEvent', 'UNHANDLED');
        EventQueue event = new EventQueue(eventQueueRecord, null, new EventQueueRepository());

        // When
        event.delivered().save();
        
        // Then
        EventQueue__c savedEventQueue = [SELECT Id, EventName__c, Status__c FROM EventQueue__c WHERE Id = :event.getId()];
        System.assertEquals('TestEvent', savedEventQueue.EventName__c);
        System.assertEquals( EventQueueStatusType.DELIVERED.name() , savedEventQueue.Status__c);
    }
}