force-app/main/default/objects/EventQueue__c/EventQueue__c.object-meta.xml
<CustomObject>
    <description>Message Events</description>
    <label>EventQueue</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>EventQueue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EventQueues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EventQueue__c/fields/DetailedStatus__c.field-meta.xml
<CustomField>
    <fullName>DetailedStatus__c</fullName>
    <description>Error Message from internal or external System</description>
    <label>DetailedStatus</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/fields/ErrorStackTrace__c.field-meta.xml
<CustomField>
    <fullName>ErrorStackTrace__c</fullName>
    <description>Used only for error messages, fill this field using getStackTraceString() method</description>
    <label>ErrorStackTrace</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/fields/EventName__c.field-meta.xml
<CustomField>
    <fullName>EventName__c</fullName>
    <description>EventName</description>
    <label>EventName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/fields/IsRetryDisabled__c.field-meta.xml
<CustomField>
    <fullName>IsRetryDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identify if the retries should be executed for this event. If equal TRUE disable retries even if retry count is bigger than zero (can be used for errors as errors does not require retries)</description>
    <label>IsRetryDisabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/fields/RetryCount__c.field-meta.xml
<CustomField>
    <fullName>RetryCount__c</fullName>
    <defaultValue>10</defaultValue>
    <description>Identify the number of retries for this event</description>
    <label>RetryCount</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/fields/SalesforceObjectId__c.field-meta.xml
<CustomField>
    <fullName>SalesforceObjectId__c</fullName>
    <description>Salesforce Object Id</description>
    <label>SalesforceObjectId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of event</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>QUEUED</fullName>
                <default>true</default>
                <label>QUEUED</label>
            </value>
            <value>
                <fullName>DELIVERED</fullName>
            </value>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>INVALID</fullName>
            </value>
            <value>
                <fullName>SCHEDULED</fullName>
            </value>
            <value>
                <fullName>UNHANDLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/event/EventQueue.cls
/**
 * @author eduardo.bisso - dev-builder
 */
public class EventQueue {

    EventQueue__c event;

    EventConfiguration config;

    EventQueueRepository repository;
    
    public EventQueue() {
        this.event = new EventQueue__c();
        this.repository = new EventQueueRepository();
    }

    public EventQueue(EventQueue__c event) {
        this();
        this.event = event;
        this.initialize(this.event.EventName__c);
    }

    public EventQueue(String eventName) {
        this( new EventQueue__c (EventName__c = eventName) );
    }

    public void initialize(String eventName) {
        this.config = this.repository.findConfigByName(eventName);       
    }

    public String getObjectId () {
        return this.event.SalesforceObjectId__c;
    }

    public String getStatus () {
        return this.event.Status__c;
    }

    public String getExternalId () {
        return this.event.ExternalId__c;
    }

    public String getId () {
        return this.event.Id;
    }

    public Boolean useCustomOAuthFlow() {
        return String.isNotEmpty( this.config.getOAuthEventName() );
    }

    public Boolean hasError () {
        return getStatus() == EventQueueStatusType.ERROR.name();
    }

    public Boolean isIgnored () {
        return getStatus() == EventQueueStatusType.IGNORED.name();
    }

    public Boolean isUnhandled () {
        return getStatus() == EventQueueStatusType.UNHANDLED.name();
    }

    public EventQueue withConfiguration (EventConfiguration config) {
        this.config = config;
        return this;
    }

    public EventQueue withStatusDetail (String detailedStatus) {
        this.event.DetailedStatus__c = detailedStatus;
        return this;
    }

    public EventQueue withStatus (EventQueueStatusType status) {
        this.event.Status__c =  status.name();
        return this;
    }

    public EventQueue withStackTrace (String stackTrace) {
        this.event.ErrorStackTrace__c =  stackTrace;
        return this;
    }

    public EventQueue withError (Exception e) {
        return withError(e, e.getTypeName() + ' :  { ' +  e.getMessage() + ' }' );
    }
    
    public EventQueue withError (DmlException e) {                
        return withError( e, e.getTypeName() + ' :  { ' +  e.getDmlMessage(0) + ' }' );
    }
    
    public EventQueue withError (Exception e, String errorMessage) {
        
        return withStatus( EventQueueStatusType.ERROR )
            .withStatusDetail(errorMessage)
            .withStackTrace(e.getStackTraceString());

    }

    public EventQueue disableRetry () {
        this.event.RetryCount__c = 0;
        this.event.IsRetryDisabled__c = true;
        return this;        
    }

    public EventQueue decreaseRetry () {
        if (this.event.RetryCount__c == 0) return this;
        this.event.retryCount__c -=  1;
        return this;        
    }

    public EventConfiguration getConfig() {
        return this.config;
    }

    public OutboundEventConfig getOutboundConfig() {
        return this.config.getOutboundConfig();
    }

    public EventQueue getOAuthEvent() {

        if (!useCustomOAuthFlow()) return null;

        return new EventQueue( this.config.getOAuthEventName() );
    }

    public void setRepository (EventQueueRepository repository) {
        this.repository = repository;
    }

    public void log () {
        //
    }
 
    public EventQueue save () {
        
        this.repository.save(this.event);      

        return this;
    }

}