force-app/main/default/objects/EventQueue__c/EventQueue__c.object-meta.xml
<CustomObject>
    <description>Message Events</description>
    <label>EventQueue</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>EventQueue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EventQueues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EventQueue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of event</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>QUEUED</fullName>
                <default>true</default>
                <label>QUEUED</label>
            </value>
            <value>
                <fullName>DELIVERED</fullName>
            </value>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>INVALID</fullName>
            </value>
            <value>
                <fullName>SCHEDULED</fullName>
            </value>
            <value>
                <fullName>UNHANDLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/event/consumer/EventQueueInterceptor.cls
public class EventQueueInterceptor {

    public static Integer totalOfRecordsInFutureCall = EventExecutorLimits.FUTURE_CALL_LIMIT * EventExecutorLimits.FUTURE_CALL_SIZE;

    public EventQueueInterceptor onBatchOrFutureAutoScheduleEvents (List<EventQueue__c> events) {

        if (!System.isBatch() && !System.isFuture()) {
            return this;
        }

        applyStatusOnEvents (events, EventQueueStatusType.SCHEDULED.name());

        return this;

    }

    public EventQueueInterceptor onFutureLimitClosedAutoScheduleEvents (List<EventQueue__c> events) {
                   
        if (Lists.isEmpty(events)) return this;                       

        if ( EventExecutorLimits.TOTAL_RECORDS_IN_FUTURE >= events.size() 
             && EventDequeuer.executedFutureCalls <= EventExecutorLimits.FUTURE_CALL_LIMIT ) {
            
            return this;
        }

        if ( EventDequeuer.executedFutureCalls >= EventExecutorLimits.FUTURE_CALL_LIMIT) {
            totalOfRecordsInFutureCall = 0;
        }
        
        for (Integer i = totalOfRecordsInFutureCall; i < events.size(); i++) {
            events.get(i).Status__c = EventQueueStatusType.SCHEDULED.name();            
        }

        return this;

    }


    private void applyStatusOnEvents (List<EventQueue__c> events, String status) {

        for (EventQueue__c event : events) {
            event.Status__c = status;
        }

    }

}