force-app/main/default/objects/EventOutboundEnvironment__mdt/EventOutboundEnvironment__mdt.object-meta.xml
<CustomObject>
    <description>EventOutboundEnvironment</description>
    <label>EventOutboundEnvironment</label>
    <pluralLabel>EventOutboundEnvironments</pluralLabel>
</CustomObject>

force-app/main/default/objects/EventOutboundEnvironment__mdt/fields/OrgEnvironment__c.field-meta.xml
<CustomField>
    <fullName>OrgEnvironment__c</fullName>
    <label>OrgEnvironment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DEVELOP</fullName>
                <default>true</default>
                <label>DEVELOP</label>
            </value>
            <value>
                <fullName>SCRATCH</fullName>
            </value>
            <value>
                <fullName>SANDBOX</fullName>
            </value>
            <value>
                <fullName>PRODUCTION</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EventOutboundEnvironment__mdt/fields/OrgNames__c.field-meta.xml
<CustomField>
    <fullName>OrgNames__c</fullName>
    <description>Inform correlated Org Name by Comma-separated values</description>
    <label>OrgNames</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventOutboundEnvironment__mdt/fields/OutboundEnvironment__c.field-meta.xml
<CustomField>
    <fullName>OutboundEnvironment__c</fullName>
    <label>Outbound Environment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DEVELOPMENT</fullName>
                <default>true</default>
                <label>DEVELOPMENT</label>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/outbound-service/http-request/OutboundEnvironmentResolver.cls
/**
 * @author eduardo.bisso - dev-builder
 */
public virtual class OutboundEnvironmentResolver {
    
    Environment env;

    public OutboundEnvironmentResolver () {
        this.env = Environment.get();
    }

    public OutboundEnvironmentResolver (Environment env) {        
        this();
        this.env = env;
    }

    public String buidOutboundEnvironment () {

        EventOutboundEnvironment__mdt env = findEnvironment ();

        return env?.OutboundEnvironment__c;
    }


    public EventOutboundEnvironment__mdt findEnvironment () {

        String orgName = '%' + env.getOrgName() + '%';

        List<EventOutboundEnvironment__mdt> enviroments = [SELECT OutboundEnvironment__c
                                                                FROM EventOutboundEnvironment__mdt 
                                                                WHERE  OrgEnvironment__c = :env.getType().name()
                                                                AND OrgNames__c LIKE :orgName ];

        return (EventOutboundEnvironment__mdt) Lists.getFirstOrNull (enviroments);                                                                        

    }

}