force-app/main/default/objects/EventOutboundEnvironment__mdt/EventOutboundEnvironment__mdt.object-meta.xml
<CustomObject>
    <description>EventOutboundEnvironment</description>
    <label>EventOutboundEnvironment</label>
    <pluralLabel>EventOutboundEnvironments</pluralLabel>
</CustomObject>

force-app/main/default/objects/EventOutboundEnvironment__mdt/fields/OutboundEnvironment__c.field-meta.xml
<CustomField>
    <fullName>OutboundEnvironment__c</fullName>
    <label>Outbound Environment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DEVELOPMENT</fullName>
                <default>true</default>
                <label>DEVELOPMENT</label>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/outbound-service/http-request/environment-resolver/OutboundEnvironmentResolverTest.cls
/**
 * @author eduardo.bisso - dev-builder
 */
@isTest
public class OutboundEnvironmentResolverTest {
    
    @isTest
    public static void shouldReturnOutboundEnvironment() {
        
        Assert.areEqual( 'DEV', newOutboundEnvironmentResolver().buidOutboundEnvironment() );

    }

    @isTest
    public static void shouldNullOutboundEnvironment() {
        
        Assert.areEqual( null, newNullOutboundEnvironmentResolver().buidOutboundEnvironment() );

    }


    public static OutboundEnvironmentResolver newOutboundEnvironmentResolver () {

        String payload = '[{"OutboundEnvironment__c":"DEV"}]';

        Environment env = EnvironmentTest.newEnvironment('dev-builder-dev-ed.develop.lightning.force.com');

        return new OutboundEnvironmentResolverMock(payload, env);
    }


    public static OutboundEnvironmentResolver newNullOutboundEnvironmentResolver () {

        Environment env = EnvironmentTest.newEnvironment('xpto.develop.lightning.force.com');

        return new OutboundEnvironmentResolver(env);
    }


    public class OutboundEnvironmentResolverMock extends OutboundEnvironmentResolver {
        String payload;

        public OutboundEnvironmentResolverMock(String payload, Environment env) {
            super(env);
            this.payload = payload;
        }

        override
        protected List<EventOutboundEnvironment__mdt> findByOrgNameAndEnvironmentType (String orgName, String environment ) {

            return (List<EventOutboundEnvironment__mdt>) JSON.deserialize(payload, List<EventOutboundEnvironment__mdt>.class);

        }

    }

}