force-app/main/default/objects/EventOutboundConfig__mdt/EventOutboundConfig__mdt.object-meta.xml
<CustomObject>
    <description>Configuração de Saída</description>
    <label>Event Outbound Configuration</label>
    <pluralLabel>EventOutboundConfigs</pluralLabel>
</CustomObject>

force-app/main/default/objects/EventOutboundConfig__mdt/fields/CertificateName__c.field-meta.xml
<CustomField>
    <fullName>CertificateName__c</fullName>
    <description>Nome do Certificado</description>
    <label>CertificateName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventOutboundConfig__mdt/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <description>End Point Url</description>
    <label>EndPoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventOutboundConfig__mdt/fields/HttpHeaders__c.field-meta.xml
<CustomField>
    <fullName>HttpHeaders__c</fullName>
    <defaultValue>&apos;{&quot;Content-Type&quot; : &quot;application/json&quot;}&apos;</defaultValue>
    <description>Json que representa os headers padrões</description>
    <label>HttpHeaders</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EventOutboundConfig__mdt/fields/HttpMethod__c.field-meta.xml
<CustomField>
    <fullName>HttpMethod__c</fullName>
    <description>HttpMethod</description>
    <label>Http Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EventOutboundConfig__mdt/fields/NamedCredencial__c.field-meta.xml
<CustomField>
    <fullName>NamedCredencial__c</fullName>
    <description>Credencial Nomeada</description>
    <label>NamedCredencial</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventOutboundConfig__mdt/fields/ResponseClassName__c.field-meta.xml
<CustomField>
    <fullName>ResponseClassName__c</fullName>
    <description>Response class name</description>
    <label>ResponseClassName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventOutboundConfig__mdt/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <defaultValue>1200000</defaultValue>
    <description>Timeout padrão</description>
    <label>Timeout</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/event/configuration/OutboundEventConfig.cls
/**
 * @author eduardo.bisso - dev-builder
 */
public class OutboundEventConfig {

    String endPointUrl;

    Integer timeout;
   
    String certificateName;

    String httpMethod;

    String httpHeaders;

    String namedCredencial;

    String responseClassName;

    public OutboundEventConfig() {
        this.timeout = 12000;
    }

    public OutboundEventConfig(EventOutboundConfig__mdt config) {

        this();

        endPointUrl(config.EndPoint__c)
            .timeout(config?.Timeout__c?.intValue() ?? 120000)
            .certificateName(config.CertificateName__c)
            .httpMethod(config.HttpMethod__c)
            .httpHeaders(config.HttpHeaders__c)
            .namedCredencial(config.NamedCredencial__c)
            .responseClassName(config.ResponseClassName__c);
    }

    public OutboundEventConfig endPointUrl(String endPointUrl) {
        this.endPointUrl = endPointUrl;
        return this;
    }

    public OutboundEventConfig timeout(Integer timeout) {
        this.timeout = timeout;

        return this;
    }

    public OutboundEventConfig certificateName(String certificateName) {
        this.certificateName = certificateName;
        return this;
    }

    public OutboundEventConfig httpMethod(String httpMethod) {
        this.httpMethod = httpMethod;
        return this;
    }

    public OutboundEventConfig httpHeaders( String httpHeaders ) {
        this.httpHeaders = httpHeaders;
        return this;
    }

    public OutboundEventConfig namedCredencial(String namedCredencial) {
        this.namedCredencial = namedCredencial;
        return this;
    }

    public OutboundEventConfig responseClassName(String responseClassName) {
        this.responseClassName = responseClassName;
        return this;
    }

    public String getEndPointUrl() {
        return this.endPointUrl;
    }

    public Integer getTimeout() {
        return this.timeout;
    }

    public String getCertificateName() {
        return this.certificateName;
    }

    public String getHttpMethod() {
        return this.httpMethod;
    }

    public String getHttpHeaders() { 
        return this.httpHeaders;
    }

    public String getNamedCredencial() {
        return this.namedCredencial;
    }

    public String getResponseClassName() {
        return this.responseClassName;
    }

}