force-app/main/default/objects/EventOutboundConfig__mdt/EventOutboundConfig__mdt.object-meta.xml
<CustomObject>
    <description>Configuração de Saída</description>
    <label>Event Outbound Configuration</label>
    <pluralLabel>EventOutboundConfigs</pluralLabel>
</CustomObject>

force-app/main/default/objects/EventOutboundConfig__mdt/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <description>End Point Url</description>
    <label>EndPoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventOutboundConfig__mdt/fields/HttpHeaders__c.field-meta.xml
<CustomField>
    <fullName>HttpHeaders__c</fullName>
    <defaultValue>&apos;{&quot;Content-Type&quot; : &quot;application/json&quot;}&apos;</defaultValue>
    <description>Json que representa os headers padrões</description>
    <label>HttpHeaders</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EventOutboundConfig__mdt/fields/HttpMethod__c.field-meta.xml
<CustomField>
    <fullName>HttpMethod__c</fullName>
    <description>HttpMethod</description>
    <label>Http Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EventOutboundConfig__mdt/fields/NamedCredencial__c.field-meta.xml
<CustomField>
    <fullName>NamedCredencial__c</fullName>
    <description>Credencial Nomeada</description>
    <label>NamedCredencial</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventOutboundConfig__mdt/fields/ResponseClassName__c.field-meta.xml
<CustomField>
    <fullName>ResponseClassName__c</fullName>
    <description>Response class name</description>
    <label>ResponseClassName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventOutboundConfig__mdt/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <defaultValue>1200000</defaultValue>
    <description>Timeout padrão</description>
    <label>Timeout</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EventOutboundConfig__mdt/fields/UseEnvironmentWithCredential__c.field-meta.xml
<CustomField>
    <fullName>UseEnvironmentWithCredential__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Use environment to define Named Credential</description>
    <label>useEnvironmentWithCredential</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/event/configuration/test/OutboundEventConfigFixtureFactory.cls
@isTest
public class OutboundEventConfigFixtureFactory {

    public static EventOutboundConfig__mdt newEventOutboundConfig( String responseClassName ) {
        return new EventOutboundConfig__mdt(
            UseEnvironmentWithCredential__c = true,
            NamedCredencial__c = 'TestNamedCredential',
            EndPoint__c = 'test/endpoint',
            Timeout__c = 15000,
            HttpMethod__c = 'POST',
            HttpHeaders__c = '{"Content-Type": "application/json"}',
            ResponseClassName__c = responseClassName
        );
    }


    public static OutboundEventConfig newOutboundConfig (String responseClassName) {
        return new OutboundEventConfig ( newEventOutboundConfig(responseClassName)  );
    }

}