force-app/main/default/objects/EventOutboundConfig__mdt/EventOutboundConfig__mdt.object-meta.xml
<CustomObject>
    <description>Configuração de Saída</description>
    <label>Event Outbound Configuration</label>
    <pluralLabel>EventOutboundConfigs</pluralLabel>
</CustomObject>

force-app/main/default/objects/EventOutboundConfig__mdt/fields/ResponseClassName__c.field-meta.xml
<CustomField>
    <fullName>ResponseClassName__c</fullName>
    <description>Response class name</description>
    <label>ResponseClassName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/outbound-service/http-request/HttpResponseBuilder.cls
/**
 * @author eduardo.bisso - dev-builder
 */
public virtual class HttpResponseBuilder {

    EventOutboundConfig__mdt config;

    public HttpResponseBuilder(EventOutboundConfig__mdt config) {
        this.config = config;
    }

    virtual
    public Object buildReponse ( HttpResponse response ) {

        Type classType = Type.forName (this.config.ResponseClassName__c);

        return JSON.deserialize(response.getBody() , classType);

    }


}