force-app/main/default/objects/EventConfiguration__mdt/EventConfiguration__mdt.object-meta.xml
<CustomObject>
    <description>Configuração do evento</description>
    <label>EventConfiguration</label>
    <pluralLabel>EventConfigurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/EventConfiguration__mdt/fields/CommandClassName__c.field-meta.xml
<CustomField>
    <fullName>CommandClassName__c</fullName>
    <description>Nome da classe responsável por implementar a Interface Command</description>
    <label>CommandClassName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventConfiguration__mdt/fields/Disabled__c.field-meta.xml
<CustomField>
    <fullName>Disabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Use this field to block event execution</description>
    <label>Disbled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EventConfiguration__mdt/fields/EnableTraceLog__c.field-meta.xml
<CustomField>
    <fullName>EnableTraceLog__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Habilita o armazenamento de Log para esse evento, assim como dados da request e response para eventos de outbound</description>
    <label>EnableTraceLog</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EventConfiguration__mdt/fields/OAuthEventName__c.field-meta.xml
<CustomField>
    <fullName>OAuthEventName__c</fullName>
    <description>Use this field to specify Event Name for Custom Authentication flow</description>
    <label>OAuthEventName</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventConfiguration__mdt/fields/OutboundConfig__c.field-meta.xml
<CustomField>
    <fullName>OutboundConfig__c</fullName>
    <description>Outbound Config</description>
    <label>Event Outbound Configuration</label>
    <referenceTo>EventOutboundConfig__mdt</referenceTo>
    <relationshipLabel>EventConfigurations</relationshipLabel>
    <relationshipName>EventConfigurations</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/EventConfiguration__mdt/fields/Retry__c.field-meta.xml
<CustomField>
    <fullName>Retry__c</fullName>
    <defaultValue>10</defaultValue>
    <description>Identify the number of retries for this event</description>
    <label>Retry</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EventOutboundConfig__mdt/EventOutboundConfig__mdt.object-meta.xml
<CustomObject>
    <description>Configuração de Saída</description>
    <label>Event Outbound Configuration</label>
    <pluralLabel>EventOutboundConfigs</pluralLabel>
</CustomObject>

force-app/main/default/objects/EventOutboundConfig__mdt/fields/CertificateName__c.field-meta.xml
<CustomField>
    <fullName>CertificateName__c</fullName>
    <description>Nome do Certificado</description>
    <label>CertificateName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventOutboundConfig__mdt/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <description>End Point Url</description>
    <label>EndPoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventOutboundConfig__mdt/fields/HttpHeaders__c.field-meta.xml
<CustomField>
    <fullName>HttpHeaders__c</fullName>
    <defaultValue>&apos;{&quot;Content-Type&quot; : &quot;application/json&quot;}&apos;</defaultValue>
    <description>Json que representa os headers padrões</description>
    <label>HttpHeaders</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EventOutboundConfig__mdt/fields/HttpMethod__c.field-meta.xml
<CustomField>
    <fullName>HttpMethod__c</fullName>
    <description>HttpMethod</description>
    <label>Http Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EventOutboundConfig__mdt/fields/NamedCredencial__c.field-meta.xml
<CustomField>
    <fullName>NamedCredencial__c</fullName>
    <description>Credencial Nomeada</description>
    <label>NamedCredencial</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventOutboundConfig__mdt/fields/OAuthClientIdCredentialVariable__c.field-meta.xml
<CustomField>
    <fullName>OAuthClientIdCredentialVariable__c</fullName>
    <inlineHelpText>Inform named Credential bind variable, exemple: {!$Credential.MyCredential.ClientId}</inlineHelpText>
    <label>OAuth ClientId Credential Variable</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventOutboundConfig__mdt/fields/OAuthClientSecretCredentialVariable__c.field-meta.xml
<CustomField>
    <fullName>OAuthClientSecretCredentialVariable__c</fullName>
    <description>Inform named Credential bind variable, exemple: {!$Credential.MyCredential.ClientSecret}</description>
    <label>OAuth ClientSecret Credential Variable</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventOutboundConfig__mdt/fields/ResponseClassName__c.field-meta.xml
<CustomField>
    <fullName>ResponseClassName__c</fullName>
    <description>Response class name</description>
    <label>ResponseClassName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventOutboundConfig__mdt/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <defaultValue>1200000</defaultValue>
    <description>Timeout padrão</description>
    <label>Timeout</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EventOutboundConfig__mdt/fields/UseEnvironmentWithCredential__c.field-meta.xml
<CustomField>
    <fullName>UseEnvironmentWithCredential__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Use environment to define Named Credential</description>
    <label>useEnvironmentWithCredential</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/EventQueue__c.object-meta.xml
<CustomObject>
    <description>Message Events</description>
    <label>EventQueue</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>EventQueue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EventQueues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EventQueue__c/fields/CorrelatedNumber__c.field-meta.xml
<CustomField>
    <fullName>CorrelatedNumber__c</fullName>
    <description>Business Document Correlated Number</description>
    <label>CorrelatedNumber</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/fields/DetailedStatus__c.field-meta.xml
<CustomField>
    <fullName>DetailedStatus__c</fullName>
    <description>Error Message from internal or external System</description>
    <label>DetailedStatus</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <description>DocumentNumber</description>
    <label>DocumentNumber</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/fields/EventName__c.field-meta.xml
<CustomField>
    <fullName>EventName__c</fullName>
    <description>EventName</description>
    <label>EventName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/fields/IsRetryDisabled__c.field-meta.xml
<CustomField>
    <fullName>IsRetryDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identify if the retries should be executed for this event. If equal TRUE disable retries even if retry count is bigger than zero (can be used for errors as errors does not require retries)</description>
    <label>IsRetryDisabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/fields/RetryCount__c.field-meta.xml
<CustomField>
    <fullName>RetryCount__c</fullName>
    <defaultValue>10</defaultValue>
    <description>Identify the number of retries for this event</description>
    <label>RetryCount</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/fields/SalesforceObjectId__c.field-meta.xml
<CustomField>
    <fullName>SalesforceObjectId__c</fullName>
    <description>Salesforce Object Id</description>
    <label>SalesforceObjectId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of event</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>QUEUED</fullName>
                <default>true</default>
                <label>QUEUED</label>
            </value>
            <value>
                <fullName>DELIVERED</fullName>
            </value>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>INVALID</fullName>
            </value>
            <value>
                <fullName>SCHEDULED</fullName>
            </value>
            <value>
                <fullName>UNHANDLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/event/repository/EventQueueRepository.cls
/**
 * @author eduardo.bisso - dev-builder
 */
public inherited sharing virtual class EventQueueRepository 
                                            extends AbstractRepository {

    virtual
    public EventQueue__c findById (String id) {

        List<EventQueue__c> events = findByIds( new List<String>{id} );     

        return (EventQueue__c) Lists.getFirstOrNull(events);
    }

    virtual
    public List<EventQueue__c> findByIds (List<String> ids) {

        return [SELECT Id, EventName__c, ExternalId__c
                    , DocumentNumber__c, CorrelatedNumber__c, SalesforceObjectId__c
                    , RetryCount__c , IsRetryDisabled__c
                    , Status__c , DetailedStatus__c        
                FROM EventQueue__c
                WHERE Id IN :ids];
    }

    virtual
    public List<EventConfiguration> findConfigByNames (List<String> names) {

        return EventConfiguration.buildConfigs( [ SELECT Id, DeveloperName, CommandClassName__c
                    , EnableTraceLog__c, OAuthEventName__c, Disabled__c
                    , Retry__c, OutboundConfig__r.CertificateName__c
                    , OutboundConfig__r.EndPoint__c                    
                    , OutboundConfig__r.HttpHeaders__c
                    , OutboundConfig__r.HttpMethod__c
                    , OutboundConfig__r.NamedCredencial__c
                    , OutboundConfig__r.ResponseClassName__c
                    , OutboundConfig__r.Timeout__c
                    , OutboundConfig__r.UseEnvironmentWithCredential__c
                    , OutboundConfig__r.OAuthClientIdCredentialVariable__c
                    , OutboundConfig__r.OAuthClientSecretCredentialVariable__c
                FROM EventConfiguration__mdt 
                WHERE DeveloperName IN : names] );

    }

    virtual
    public EventConfiguration findConfigByName (String name) {

        List<EventConfiguration> configs = findConfigByNames ( new List<String> {name} );
        
        return configs.isEmpty() ? null : configs.get(0);

    }




}