force-app/main/default/objects/EventConfiguration__mdt/EventConfiguration__mdt.object-meta.xml
<CustomObject>
    <description>Configuração do evento</description>
    <label>EventConfiguration</label>
    <pluralLabel>EventConfigurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/EventConfiguration__mdt/fields/CommandClassName__c.field-meta.xml
<CustomField>
    <fullName>CommandClassName__c</fullName>
    <description>Nome da classe responsável por implementar a Interface Command</description>
    <label>CommandClassName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventConfiguration__mdt/fields/Disabled__c.field-meta.xml
<CustomField>
    <fullName>Disabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Use this field to block event execution</description>
    <label>Disbled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EventConfiguration__mdt/fields/EnableTraceLog__c.field-meta.xml
<CustomField>
    <fullName>EnableTraceLog__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Habilita o armazenamento de Log para esse evento, assim como dados da request e response para eventos de outbound</description>
    <label>EnableTraceLog</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EventConfiguration__mdt/fields/OAuthEventName__c.field-meta.xml
<CustomField>
    <fullName>OAuthEventName__c</fullName>
    <description>Use this field to specify Event Name for Custom Authentication flow</description>
    <label>OAuthEventName</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventConfiguration__mdt/fields/Retry__c.field-meta.xml
<CustomField>
    <fullName>Retry__c</fullName>
    <defaultValue>10</defaultValue>
    <description>Identify the number of retries for this event</description>
    <label>Retry</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/event/configuration/test/EventConfigurationFixtureFactory.cls
@isTest (isParallel=true)
public class EventConfigurationFixtureFactory {

    public static EventConfiguration__mdt newEventConfigurationMdt(String developerName) {
        return new EventConfiguration__mdt(
            DeveloperName = developerName,
            CommandClassName__c = 'CommandFixtureFactory.FakeCommand',
            Retry__c = 5,
            EnableTraceLog__c = true,
            OAuthEventName__c = 'TestOAuthEvent',
            Disabled__c = false            
        );
    }

    public static EventConfiguration newEventConfiguration(String developerName) {
        return new EventConfiguration(newEventConfigurationMdt(developerName));
    }


    public static EventConfiguration newEventConfigurationForOutbound (String developerName
                                                                        , String responseClassName) {
        return new EventConfiguration(newEventConfigurationMdt(developerName))
                        .outboundConfig( OutboundEventConfigFixtureFactory.newOutboundConfig(responseClassName));

    }

    public static EventConfiguration newOAuthEventConfigurationForOutbound (String developerName
                                                                         , String responseClassName) {
        
        
        EventConfiguration config = newEventConfigurationForOutbound (developerName, responseClassName);

        config.getOutboundConfig().httpMethod('POST')
                    .clientIdCredentialVariable(StringGenerator.text(10))
                    .clientSecretCredentialVariable(StringGenerator.text(10));
        
        return config;

    }
   
    public static List<EventConfiguration> newEventConfigurations(List<String> eventNames) {

        List<EventConfiguration> eventConfigs = new List<EventConfiguration>();

        for (String eventName : eventNames) {
            eventConfigs.add(newEventConfiguration(eventName));
        }
        
        return eventConfigs;
    }


}