force-app/main/default/objects/EventConfiguration__mdt/EventConfiguration__mdt.object-meta.xml
<CustomObject>
    <description>Configuração do evento</description>
    <label>EventConfiguration</label>
    <pluralLabel>EventConfigurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/EventConfiguration__mdt/fields/CommandClassName__c.field-meta.xml
<CustomField>
    <fullName>CommandClassName__c</fullName>
    <description>Nome da classe responsável por implementar a Interface Command</description>
    <label>CommandClassName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventConfiguration__mdt/fields/Disabled__c.field-meta.xml
<CustomField>
    <fullName>Disabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Use this field to block event execution</description>
    <label>Disbled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EventConfiguration__mdt/fields/EnableTraceLog__c.field-meta.xml
<CustomField>
    <fullName>EnableTraceLog__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Habilita o armazenamento de Log para esse evento, assim como dados da request e response para eventos de outbound</description>
    <label>EnableTraceLog</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EventConfiguration__mdt/fields/OAuthEventName__c.field-meta.xml
<CustomField>
    <fullName>OAuthEventName__c</fullName>
    <description>Use this field to specify Event Name for Custom Authentication flow</description>
    <label>OAuthEventName</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventConfiguration__mdt/fields/OutboundConfig__c.field-meta.xml
<CustomField>
    <fullName>OutboundConfig__c</fullName>
    <description>Outbound Config</description>
    <label>Event Outbound Configuration</label>
    <referenceTo>EventOutboundConfig__mdt</referenceTo>
    <relationshipLabel>EventConfigurations</relationshipLabel>
    <relationshipName>EventConfigurations</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/EventConfiguration__mdt/fields/Retry__c.field-meta.xml
<CustomField>
    <fullName>Retry__c</fullName>
    <defaultValue>10</defaultValue>
    <description>Identify the number of retries for this event</description>
    <label>Retry</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EventOutboundConfig__mdt/EventOutboundConfig__mdt.object-meta.xml
<CustomObject>
    <description>Configuração de Saída</description>
    <label>Event Outbound Configuration</label>
    <pluralLabel>EventOutboundConfigs</pluralLabel>
</CustomObject>

force-app/main/default/classes/event/configuration/EventConfiguration.cls
/**
 * @author eduardo.bisso - dev-builder
 */
public class EventConfiguration {
    
    String eventName;
    
    String commandClassName;    
    
    OutboundEventConfig outboundConfig;
    
    String oAuthEventName;

    Boolean disabled;
    Boolean enableTraceLog;
    Integer retry;

    public EventConfiguration() {
        this.retry = 10;
        this.disabled = false;
        this.enableTraceLog = true;
    }

    public EventConfiguration(EventConfiguration__mdt config) {

        this();
        
        if (config == null) return;

        eventName (config.DeveloperName)
            .commandClassName(config.CommandClassName__c)            
            .retryCount( config.Retry__c?.intValue() ?? 10 )
            .enableTraceLog(config.EnableTraceLog__c ?? true )
            .oauthEventName( config.OAuthEventName__c )
            .disabled(config.Disabled__c ?? false);

        if (config.OutboundConfig__r != null) {
            outboundConfig( new OutboundEventConfig(config.OutboundConfig__r));
        }
    }

    public String getEventName () {
        return this.eventName;
    }

    public String getCommandClassName() {
        return this.commandClassName;
    }

    public OutboundEventConfig getOutboundConfig() {
        return this.outboundConfig;
    }

    public Boolean isDisabled() {
        return this.disabled;
    }

    public Boolean isEnableTraceLog() {
        return this.enableTraceLog;
    }

    public Integer getRetry() {
        return this.retry;
    }

    public String getOAuthEventName () {
        return this.oAuthEventName;
    }

    public EventConfiguration eventName (String eventName) {
        this.eventName = eventName;
        return this;
    }    

    public EventConfiguration commandClassName(String commandClassName) {
        this.commandClassName = commandClassName;
        return this;
    }

    public EventConfiguration outboundConfig(OutboundEventConfig outboundConfig) {
        this.outboundConfig = outboundConfig;
        return this;
    }

    public EventConfiguration disabled(Boolean disabled) {
        this.disabled = disabled;
        return this;
    }

    public EventConfiguration enableTraceLog(Boolean enableTraceLog) {
        this.enableTraceLog = enableTraceLog;
        return this;
    }

    public EventConfiguration retryCount(Integer retry) {
        this.retry = retry;
        return this;
    }

    public EventConfiguration oauthEventName (String oauthEventName) {
        this.oAuthEventName = oauthEventName;
        return this;
    }
    
    public Boolean hasCommandHandler () {
        return this.commandClassName != null;
    }

    public Command getCommand () {
        return CommandFactory.newInstance(getCommandClassName());
    }

    public static List<EventConfiguration> buildConfigs (List<EventConfiguration__mdt> configs) {

        List<EventConfiguration> eventConfigs = new  List<EventConfiguration>();

        for (EventConfiguration__mdt config: configs) {

            eventConfigs.add ( new EventConfiguration(config) );
        }

        return eventConfigs;

    }

}