force-app/main/default/objects/EventConfiguration__mdt/EventConfiguration__mdt.object-meta.xml
<CustomObject>
    <description>Configuração do evento</description>
    <label>EventConfiguration</label>
    <pluralLabel>EventConfigurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/EventConfiguration__mdt/fields/CommandClassName__c.field-meta.xml
<CustomField>
    <fullName>CommandClassName__c</fullName>
    <description>Nome da classe responsável por implementar a Interface Command</description>
    <label>CommandClassName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventConfiguration__mdt/fields/EnableTraceLog__c.field-meta.xml
<CustomField>
    <fullName>EnableTraceLog__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Habilita o armazenamento de Log para esse evento, assim como dados da request e response para eventos de outbound</description>
    <label>EnableTraceLog</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EventConfiguration__mdt/fields/OutboundConfig__c.field-meta.xml
<CustomField>
    <fullName>OutboundConfig__c</fullName>
    <description>Outbound Config</description>
    <label>Event Outbound Configuration</label>
    <referenceTo>EventOutboundConfig__mdt</referenceTo>
    <relationshipLabel>EventConfigurations</relationshipLabel>
    <relationshipName>EventConfigurations</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/EventConfiguration__mdt/fields/Retry__c.field-meta.xml
<CustomField>
    <fullName>Retry__c</fullName>
    <defaultValue>10</defaultValue>
    <description>Identify the number of retries for this event</description>
    <label>Retry</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EventOutboundConfig__mdt/EventOutboundConfig__mdt.object-meta.xml
<CustomObject>
    <description>Configuração de Saída</description>
    <label>Event Outbound Configuration</label>
    <pluralLabel>EventOutboundConfigs</pluralLabel>
</CustomObject>

force-app/main/default/objects/EventOutboundConfig__mdt/fields/CertificateName__c.field-meta.xml
<CustomField>
    <fullName>CertificateName__c</fullName>
    <description>Nome do Certificado</description>
    <label>CertificateName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventOutboundConfig__mdt/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <description>End Point Url</description>
    <label>EndPoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventOutboundConfig__mdt/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <description>Ambiente que será executado</description>
    <label>Enviroment</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DEV</fullName>
                <default>true</default>
                <label>DEV</label>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>PROD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EventOutboundConfig__mdt/fields/HttpHeaders__c.field-meta.xml
<CustomField>
    <fullName>HttpHeaders__c</fullName>
    <defaultValue>&apos;{&quot;Content-Type&quot; : &quot;application/json&quot;}&apos;</defaultValue>
    <description>Json que representa os headers padrões</description>
    <label>HttpHeaders</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EventOutboundConfig__mdt/fields/HttpMethod__c.field-meta.xml
<CustomField>
    <fullName>HttpMethod__c</fullName>
    <description>HttpMethod</description>
    <label>Http Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EventOutboundConfig__mdt/fields/NamedCredencial__c.field-meta.xml
<CustomField>
    <fullName>NamedCredencial__c</fullName>
    <description>Credencial Nomeada</description>
    <label>NamedCredencial</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventOutboundConfig__mdt/fields/ResponseClassName__c.field-meta.xml
<CustomField>
    <fullName>ResponseClassName__c</fullName>
    <description>Response class name</description>
    <label>ResponseClassName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EventOutboundConfig__mdt/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <defaultValue>1200000</defaultValue>
    <description>Timeout padrão</description>
    <label>Timeout</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EventQueue__c/EventQueue__c.object-meta.xml
<CustomObject>
    <description>Message Events</description>
    <label>EventQueue</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>EventQueue</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EventQueues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/event/EventQueueRepository.cls
/**
 * @author eduardo.bisso - dev-builder
 */
public inherited sharing virtual class EventQueueRepository 
                                            extends AbstractRepository {

    public EventQueueRepository() {
    }    

    public EventQueue__c findById (String id) {

        return [SELECT Id FROM EventQueue__c];
    }

    public EventConfiguration__mdt findConfigByName (String name) {

        return [ SELECT Id 
                , DeveloperName
                , CommandClassName__c
                , EnableTraceLog__c
                , Retry__c
                , OutboundConfig__r.CertificateName__c
                , OutboundConfig__r.EndPoint__c
                , OutboundConfig__r.Environment__c
                , OutboundConfig__r.HttpHeaders__c
                , OutboundConfig__r.HttpMethod__c
                , OutboundConfig__r.NamedCredencial__c
                , OutboundConfig__r.ResponseClassName__c
                , OutboundConfig__r.Timeout__c                
                FROM EventConfiguration__mdt WHERE DeveloperName =: name];

    }




}