force-app/main/default/objects/ChainedTriggerInterceptor__mdt/ChainedTriggerInterceptor__mdt.object-meta.xml
<CustomObject>
    <label>Chained Trigger Interceptor</label>
    <pluralLabel>Chained Trigger Interceptors</pluralLabel>
</CustomObject>

force-app/main/default/objects/ChainedTriggerInterceptor__mdt/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <label>Object Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ChainedTriggerInterceptor__mdt/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ChainedTriggerInterceptor__mdt/fields/TriggerFilterName__c.field-meta.xml
<CustomField>
    <fullName>TriggerFilterName__c</fullName>
    <description>TriggerFilterName</description>
    <label>Trigger Filter Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/base-framework/trigger-handler/chainedtrigger/TriggerInterceptorRepository.cls
public virtual class TriggerInterceptorRepository {
    
    virtual
    public List<ChainedTriggerInterceptor__mdt> findByObjectAndTriggerEvent (String objectName, String operationType) {

        return [ SELECT DeveloperName, ObjectName__c, Sequence__c, TriggerFilterName__c 
                FROM ChainedTriggerInterceptor__mdt
                WHERE ObjectName__c = :objectName
                AND TriggerOperationType__c =: operationType
                ORDER BY Sequence__c ASC
            ];
    }

}