force-app/main/default/objects/ChainedTriggerInterceptor__mdt/ChainedTriggerInterceptor__mdt.object-meta.xml
<CustomObject>
    <label>Chained Trigger Interceptor</label>
    <pluralLabel>Chained Trigger Interceptors</pluralLabel>
</CustomObject>

force-app/main/default/objects/ChainedTriggerInterceptor__mdt/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <label>Object Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ChainedTriggerInterceptor__mdt/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ChainedTriggerInterceptor__mdt/fields/TriggerFilterName__c.field-meta.xml
<CustomField>
    <fullName>TriggerFilterName__c</fullName>
    <description>TriggerFilterName</description>
    <label>Trigger Filter Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/base-framework/trigger-handler/chainedtrigger/TriggerInterceptorConfig.cls
public class TriggerInterceptorConfig {

    String objectName;

    String interceptorClass;

    String triggerFilterClass;

    String triggerOperation;

    Integer sequence;

    public TriggerInterceptorConfig() {
        this.sequence = 0;
    }

    public TriggerInterceptorConfig(ChainedTriggerInterceptor__mdt config) {
        objectName (config.ObjectName__c)
        .interceptorClass(config.InterceptorClass__c )
        .sequence(config.Sequence__c)
        .triggerOperation ( config.TriggerOperationType__c)
        .triggerFilterClass ( config.TriggerFilterName__c );
    }

    public String getObjectName() {
        return this.objectName;
    }

    public String getInterceptorClass() {
        return this.interceptorClass;
    }

    public String getTriggerFilterClass() {
        return this.triggerFilterClass;
    }

    public String getTriggerOperation() {
        return this.triggerOperation;
    }

    public Integer getSequence() {
        return this.sequence;
    }

    public TriggerInterceptorConfig objectName(String objectName) {
        this.objectName = objectName;
        return this;
    }

    public TriggerInterceptorConfig interceptorClass(String interceptorClass) {
        this.interceptorClass = interceptorClass;
        return this;
    }

    public TriggerInterceptorConfig triggerFilterClass(String triggerFilterClass) {
        this.triggerFilterClass = triggerFilterClass;
        return this;
    }

    public TriggerInterceptorConfig triggerOperation(String triggerOperation) {
        this.triggerOperation = triggerOperation;
        return this;
    }

    public TriggerInterceptorConfig sequence(Decimal sequence) {
        this.sequence = sequence.intValue();
        return this;
    }

    override
    public String toString () {
        return JSON.serialize(this);
    }

}